---

#
# Sets up a cluster of nats servers
#
- name: fetch NATS release
  tags: install_nats
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  get_url:
    url: https://github.com/nats-io/nats-server/releases/download/v2.3.4/nats-server-v2.3.4-amd64.deb
    dest: /tmp/nats-server-v2.3.4-amd64.deb
    checksum: sha256:9f60a6fefc580bb6a6bed4597d7fb8bae1ab9ca1d8475956fe524991b2478285

- name: install NATS
  tags: install_nats
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true
  apt: deb="/tmp/nats-server-v2.3.4-amd64.deb"

- name: create NATS dir
  file: path=/etc/nats owner=nobody group=nogroup mode=0755 state=directory
  tags: install_nats

- name: create NATS lib dir
  file: path=/var/lib/nats owner=nobody group=nogroup mode=0755 state=directory
  tags: install_nats

- name: create NATS log dir
  file: path=/var/log/nats owner=nobody group=nogroup mode=0755 state=directory
  tags: install_nats

- name: install config file
  template: src=server.conf.j2 dest=/etc/nats/server.conf
  tags: install_nats

- name: add server unit
  tags: install_nats
  template: src=nats_server.service.j2 dest=/etc/systemd/system/nats_server.service owner=root group=root

- name: start nats-server
  tags: install_nats
  block:
    - name: start systemd daemon
      systemd: enabled=yes name=nats_server.service state=started daemon_reload=yes
  rescue:
    - name: start server in shell
      shell: "(nats-server -c /etc/nats/server.conf -l /var/log/nats/nats.log &)"
      become: true
      async: 10
      poll: 0

- name: install nats-top
  get_url:
    url: https://github.com/nats-io/nats-top/releases/download/v0.4.0/nats-top-v0.4.0-amd64.deb
    dest: /tmp/nats-top-v0.4.0-amd64.deb
    checksum: sha256:5115e53e67191c1944bf2602fee8d2a2b063ad61cfc18fa16d1342c195ba54bf

- name: install nats-top
  become: true
  apt: deb="/tmp/nats-top-v0.4.0-amd64.deb"

- name: install nats-cli
  get_url:
    url: https://github.com/nats-io/natscli/releases/download/0.0.25/nats-0.0.25-amd64.deb
    dest: /tmp/nats-0.0.25-amd64.deb
    checksum: sha256:9401eefe703e5a40c17edcdf21a441fa83f26a9755975e30e39327cc1c1d42dd

- name: install nats-cli
  become: true
  apt: deb="/tmp/nats-0.0.25-amd64.deb"

- name: check nats online
  block:
    - name: shell exec
      shell: nats --user={{ nats_auth_user }} --password={{ nats_auth_password }} server ping
      become: true
  rescue:
    - name: Print when errors
      shell: "cat /var/log/nats/nats.log"

